USE [master]
GO
/****** Object:  Database [CoreDB]    Script Date: 1/1/2021 9:13:26 p.m. ******/
CREATE DATABASE [CoreDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoreDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CoreDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CoreDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CoreDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [CoreDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoreDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CoreDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CoreDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CoreDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CoreDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CoreDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CoreDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CoreDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CoreDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CoreDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CoreDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CoreDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CoreDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CoreDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CoreDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CoreDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CoreDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CoreDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CoreDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CoreDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CoreDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CoreDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CoreDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CoreDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CoreDB] SET  MULTI_USER 
GO
ALTER DATABASE [CoreDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CoreDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CoreDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CoreDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CoreDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CoreDB] SET QUERY_STORE = OFF
GO
USE [CoreDB]
GO
/****** Object:  Table [dbo].[tblClientes]    Script Date: 1/1/2021 9:13:26 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblClientes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cedula] [nvarchar](13) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Apellido] [nvarchar](50) NOT NULL,
	[Sexo] [char](10) NOT NULL,
	[FechaNacimiento] [date] NOT NULL,
	[ProductosActivos] [int] NOT NULL,
	[Telefono] [nchar](10) NOT NULL,
	[CodigoPostal] [nchar](5) NOT NULL,
	[Estado] [nvarchar](50) NOT NULL,
	[Ciudad] [nchar](50) NOT NULL,
	[Direccion] [nvarchar](max) NOT NULL,
	[Correo] [nvarchar](70) NOT NULL,
	[Celular] [nchar](10) NOT NULL,
	[ProductosTotales] [int] NOT NULL,
	[ProductoInactivos] [int] NOT NULL,
	[FechaRegistro] [date] NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_tblClientes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblCuenta]    Script Date: 1/1/2021 9:13:27 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblCuenta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CedulaCliente] [nchar](13) NULL,
	[Numero] [nchar](10) NULL,
	[FechaCreacion] [date] NULL,
	[Estado] [bit] NULL,
	[BalanceDisponible] [real] NULL,
	[BalanceTotal] [real] NULL,
	[PenultimoBalance] [real] NULL,
	[UltimoUso] [date] NULL,
	[TipoCuenta] [nvarchar](50) NULL,
	[Moneda] [nchar](10) NULL,
 CONSTRAINT [PK_tblCuenta] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblPrestamos]    Script Date: 1/1/2021 9:13:27 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblPrestamos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](max) NULL,
	[Cantidad_total] [real] NULL,
	[Cantidad_saldada] [real] NULL,
	[Cantidad_restante] [real] NULL,
	[Aprobado] [bit] NULL,
	[ClienteCed] [nvarchar](50) NULL,
 CONSTRAINT [PK_tblPrestamos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTransacciones]    Script Date: 1/1/2021 9:13:27 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTransacciones](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CuentaOrigen] [nvarchar](50) NULL,
	[CuentaDestino] [nvarchar](50) NULL,
	[Monto] [real] NULL,
	[Concepto] [nvarchar](max) NULL,
	[Fecha] [datetime] NULL,
	[Tipo] [nvarchar](50) NULL,
 CONSTRAINT [PK_tblTransacciones] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [CoreDB] SET  READ_WRITE 
GO
